namespace Jelly.Ast;

public static class Keywords
{
    public static readonly StringValue A = new("a");
    public static readonly StringValue Args = new("args");
    public static readonly StringValue ArgNames = new("argnames");
    public static readonly StringValue ArgDefaults = new("argdefaults");
    public static readonly StringValue Assignment = new("assignment");
    public static readonly StringValue B = new("b");
    public static readonly StringValue BinOp = new("binop");
    public static readonly StringValue Body = new("body");
    public static readonly StringValue Command = new("command");
    public static readonly StringValue Commands = new("commands");
    public static readonly StringValue Composite = new("composite");
    public static readonly StringValue Condition = new("condition");
    public static readonly StringValue DefineVariable = new("defvariable");
    public static readonly StringValue DefineCommand = new("defcommand");
    public static readonly StringValue Dict = new("dict");
    public static readonly StringValue Else = new("else");
    public static readonly StringValue End = new("end");
    public static readonly StringValue ErrorType = new("errortype");
    public static readonly StringValue Expression = new("expression");
    public static readonly StringValue ErrorHandlers = new("errorhandlers");
    public static readonly StringValue Finally = new("finally");
    public static readonly StringValue ForRange = new("forrange");
    public static readonly StringValue ForList = new("forlist");
    public static readonly StringValue ForDict = new("fordict");
    public static readonly StringValue If = new("if");
    public static readonly StringValue Index = new("index");
    public static readonly StringValue It = new("it");
    public static readonly StringValue ItIndex = new("it_index");
    public static readonly StringValue ItKey = new("it_key");
    public static readonly StringValue ItValue = new("it_value");
    public static readonly StringValue Key = new("key");
    public static readonly StringValue List = new("list");
    public static readonly StringValue Literal = new("literal");
    public static readonly StringValue Message = new("message");
    public static readonly StringValue Name = new("name");
    public static readonly StringValue Op = new("op");
    public static readonly StringValue Parts = new("parts");
    public static readonly StringValue Raise = new("raise");
    public static readonly StringValue RestArgName = new("restargname");
    public static readonly StringValue Scope = new("scope");
    public static readonly StringValue Script = new("script");
    public static readonly StringValue Start = new("start");
    public static readonly StringValue Step = new("step");
    public static readonly StringValue SubExpressions = new("subexpressions");
    public static readonly StringValue Then = new("then");
    public static readonly StringValue Try = new("try");
    public static readonly StringValue Type = new("type");
    public static readonly StringValue UniOp = new("uniop");
    public static readonly StringValue Value = new("value");
    public static readonly StringValue Values = new("values");
    public static readonly StringValue Variable = new("variable");
    public static readonly StringValue While = new("while");
}